config/routes.rb
Rails.application.routes.draw do
  resources :services
  get 'home/index'
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/service.rb
class Service < ApplicationRecord
  validates :name, presence: true

  # Generate a random token.
  before_create do
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index = nil
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include Xavius::Controllers::Base
  private
    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :technology, :repository_url)
    end

    alias_method :resource_params, :service_params
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu_class(controller_name)
    params[:controller] == controller_name ? "is-active" : ""
  end

  def xavius_form_with(model: nil, scope: nil, url: nil, format: nil, **options, &block)
    # TODO: replace by Xavius::Config.default_form_builder
    options[:builder] ||= Xavius::BootstrapFormBuilder
    form_with model: model, scope: scope, url: url, format: format, **options, &block
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/xavius/bootstrap_form_builder.rb
class Xavius::BootstrapFormBuilder < Xavius::FormBuilder
  LABEL_CLASS = "form-label"
  INPUT_CLASS = "form-control"

  def text_field(attribute, options = {})
    @template.content_tag(:div, class: "row mb-2") do
      label(attribute, class: LABEL_CLASS) +
      super(attribute, options.merge(class: INPUT_CLASS))
    end
  end

  def submit(value = nil, options = {})
    @template.content_tag(:div, class: "row") do
      super(value, options.merge(class: "btn btn-primary"))
    end
  end

  def input(attribute, options = {}, as: :text_field)
    send(as, attribute, options.merge(class: INPUT_CLASS))
  end
end

app/helpers/xavius/bulma_form_builder.rb
class Xavius::BulmaFormBuilder < Xavius::FormBuilder
  LABEL_CLASS = "label"

  def text_field(attribute, options = {})
    @template.content_tag(:div, class: "field") do
      label(attribute, class: LABEL_CLASS) +
      @template.content_tag(:div, class: "control") do
        super(attribute, options.merge(class: "input"))
      end
    end
  end

  def text_area(attribute, options = {})
    @template.content_tag(:div, class: "field") do
      label(attribute, class: LABEL_CLASS) +
      @template.content_tag(:div, class: "control") do
        super(attribute, options.merge(class: "textarea"))
      end
    end
  end

  def select(attribute, choices = nil, options = {}, html_options = {}, &block)
    @template.content_tag(:div, class: "field") do
      label(attribute, class: LABEL_CLASS) +
      @template.content_tag(:div, class: "control") do
        @template.content_tag(:div, class: "select") do
          super(attribute, choices, options, html_options, &block)
        end
      end
    end
  end

  def submit(value = nil, options = {})
    @template.content_tag(:div, class: "control") do
      super(value, options.merge(class: "button is-primary"))
    end
  end
end

app/helpers/xavius/form_builder.rb
class Xavius::FormBuilder < ActionView::Helpers::FormBuilder
  def input(attribute, options = {}, as: :text_field)
    @template.content_tag(:div, class: "field") do
      label(attribute, class: "label") +
      send(as, attribute, options.merge(class: "input"))
    end
  end
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<div data-controller="hello"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaveConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar bg-primary">
      <div class="container-fluid justify-content-center">
        <form class="w-25" role="search">
          <input class="form-control rounded-5" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/services/_form.html.erb
<%= xavius_form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %>
  <%= form.text_field :technology %>
  <%= form.text_field :repository_url %>

  <%= form.submit %>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>" class="card">
  <p>
    <strong>UUID:</strong>
    <%= service.uuid %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= service.name %>
  </p>

  <p>
    <strong>Technology:</strong>
    <%= service.technology %>
  </p>

  <p>
    <strong>Repository url:</strong>
    <%= service.repository_url %>
  </p>

</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Services</h1>

<div id="services">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= Service.human_attribute_name(:name) %></th>
        <th><%= Service.human_attribute_name(:technology) %></th>
        <th><%= Service.human_attribute_name(:repository_url) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
     <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.name %></td>
          <td><%= service.technology %></td>
          <td><%= service.repository_url %></td>
          <td>
            <%= link_to service do %>
              <i class="bi bi-eye-fill"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_service_path(service) do %>
              <i class="bi bi-pencil-fill"></i>
            <% end %>
          </td>
          <td>
            <%= link_to service, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
  </table>
</div>

<%= link_to "New service", new_service_path, class: "btn btn-success" %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Edit this service", edit_service_path(@service) %> |
  <%= link_to "Back to services", services_path %>

  <%= button_to "Destroy this service", @service, method: :delete %>
</div>